openapi: "3.0.1"
info:
  title: "dev-game-store-service"
  version: "2020-10-31T13:28:49Z"
servers:
  - url: "https://x5v02w7ua0.execute-api.eu-west-1.amazonaws.com/{basePath}"
    variables:
      basePath:
        default: "dev"
paths:
  /products/{id}:
    get:
      summary: "Get a game by id"
      parameters:
        - in: "path"
          name: "id"
          required: true
          schema:
            type: "string"
      responses:
        200:
          description: "A single game"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Game"
    options:
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
  /products:
    post:
      summary: "Create a new game product"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GameCreateRequest'
      responses:
        200:
          description: "Result message of product creation"
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
    get:
      summary: "Returns a list of games"
      responses:
        200:
          description: "A JSON array of games"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Game"
    options:
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
components:
  schemas:
    GameCreateRequest:
      type: object
      required:
        - title
        - description
        - price
        - count
      properties:
        title:
          type: string
        studio:
          type: string
        genre:
          type: string
        description:
          type: string
        release_date:
          type: string
        poster:
          type: string
        price:
          type: integer
        count:
          type: integer
    Game:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        studio:
          type: string
        genre:
          type: string
        description:
          type: string
        release_date:
          type: string
        poster:
          type: string
        price:
          type: integer
        count:
          type: integer
