service:
  name: game-store-authorizarion-service

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  profile: aws-test
  region: eu-west-1
  stage: dev
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB

  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  basicAuthorizer:
    handler: handler.basicAuthorizer

resources:
  Outputs:
    basicAuthorizerArn:
      Value:
        Fn::GetAtt:
          - BasicAuthorizerLambdaFunction
          - Arn
